Models/OdeToFoodDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace OdeToFood.Models
{
    public class OdeToFoodDbContext : DbContext
    {
        public OdeToFoodDbContext(DbContextOptions<OdeToFoodDbContext> options) : base(options)
        {
            
        }
        public DbSet<Restaurant> Restaurants { get; set; }

    }
}

Models/Restaurant.cs
using System.ComponentModel.DataAnnotations;

namespace OdeToFood.Models
{
    
    //ENUM type is used to hold the type of cuisine 
    //of each restaurant but you can also use a second model if you like
    public enum CuisineType
         {
             None,
             African,
             Italian,
             Indian,
             Mexican,
             Chinese
             
             
         }
    
    public enum CuisineDays
    {
        All_Days,
        Monday_Friday,
        Monday_Saturday,
        Monday_Thursday,
    }
    
    public class Restaurant
    {
        [Key]
        public int Id { get; set; }
        
        [Required, MaxLength(80)]
        [Display(Name = "Restaurant Name")]
        public string Name { get; set; }
        
        [Required]
        [Display(Name = "Restaurant location")]
        public string Location { get; set; }
        
        [Required]
        [Display(Name = "Phone number")]
        public string Phone { get; set; }
        [Required]
        [Display(Name = "Description")]
        
        public string Description { get; set; }
        
        public CuisineType Cuisine { get; set; } // reference to the enum cuisinetype
        
        [Required]
        [Display(Name = "Working days")]
        public CuisineDays CuisineDays { get; set; } 
    }
}

ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using OdeToFood.Models;

namespace OdeToFood.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
    }
}

ViewModels/RestaurantEditViewModel.cs
using System.ComponentModel.DataAnnotations;
using OdeToFood.Models;

namespace OdeToFood.ViewModels
{
    /**/
    public class RestaurantEditViewModel
    {
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
        
        public string Location { get; set; }
        public string Phone { get; set; }
        public CuisineDays Days { get; set; }
        public string Description { get; set; }
     
    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.ViewModels;

namespace OdeToFood.Controllers
{
    public class AboutController : Controller
    {
        private readonly IRestaurantData _restaurantData;

        public AboutController(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }
        // GET
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Delete(int id)
        {
            var restaurant = new Restaurant {Id = id};
              _restaurantData.DeleteRestaurant(restaurant);
              
              return RedirectToAction("Index","Home"); 

        }
        
        public IActionResult Update(int id)
        {
            ViewBag.data = _restaurantData.Get(id);
            return View();
        }
        
        [HttpPost]
        public IActionResult Update(Restaurant model)
        {
            if (ModelState.IsValid)
            {
                var restaurant = _restaurantData.Get(model.Id);               
                _restaurantData.UpdateRestaurant(restaurant);
                
                // return View("Details", restaurant);

                return RedirectToAction("Details", "Home",new {id = restaurant.Id}); // TODO :fix redirection to details

            }

            return View();
        }

        public IActionResult Help()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System.Net;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.ViewModels;

namespace OdeToFood.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRestaurantData _restaurantData;

        public HomeController(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }
        // GET
        public IActionResult Index()
        {
            // var resto = new Restaurant{Id = 1, Name = "Meze Fresh"};
            //var resto = _restaurantData.GetAll();
            var resto = new HomeViewModel();
            resto.Restaurants = _restaurantData.GetAll();
            return View(resto);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Restaurant model)
        {
            if (ModelState.IsValid)
            {
                var restaurant = new Restaurant {Name = model.Name, Cuisine = model.Cuisine,Location = model.Location,Phone = model.Phone,CuisineDays = model.CuisineDays,Description = model.Description};
                _restaurantData.Add(restaurant);

                // return View("Details", restaurant);

                return RedirectToAction("Details", new {id = restaurant.Id}); // TODO :fix redirection to details

            }
          
            return View();
        }

        public IActionResult Details(int id)
        {
            var resto = _restaurantData.Get(id);

            if (resto == null)
            {
                return RedirectToAction("Index");
            }

            return View(resto);
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeToFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - OdeToFood - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/About/Help.cshtml
@model OdeToFood.Models.Restaurant
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers 
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title>Home</title>
</head>
<body>

<div class="row justify-content-center pt-5 pb-5">
    <div class="col-lg-5">
        <div class="card" style="width: 30rem;">
            <img class="card-img-top" src="https://pngimage.net/wp-content/uploads/2018/06/table-restaurant-png.png" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">About us</h5>
                <p class="card-text">
                    
                    For more information, you call on 0787689692 and on watsup 0786115058
                </p>
            </div>
          
            <div class="card-body">
           <a class="btn btn-success" asp-action="Index" asp-controller="Home">Back to home</a>
            </div>
        </div>
    </div>
</div>



</body>
</html>

Views/About/Update.cshtml
@using OdeToFood.Models
@model OdeToFood.Models.Restaurant

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers 

@{
     Layout = "_Layout";

    Restaurant res = ViewBag.data;
    
 }
 
 <!DOCTYPE html>
<html lang="html">
 <head>
     <title>Update</title>
 </head>
 <body>
 <div class="row justify-content-center pt-3">
 <div class="col-lg-5">
     <h1>Update this restaurant</h1>
     @*You should change this form and use razor tags*@

     <form asp-action="Update" asp-controller="About" method="post">
         <div class="form-group">
             <label asp-for="Name">Name</label>
             <input type="text" asp-for="Name" class="form-control" value="@res.Name"/>
             <small aria-invalid="true"></small>
         </div>

         <div class="form-group">
             <label asp-for="Location">Location:</label>
             <input type="text" asp-for="Location" class="form-control" value="@res.Location"/>
             <small aria-invalid="true"></small>
         </div>
         
          <div class="form-group">
<select asp-for="@res.Cuisine" class="form-control">
                 @foreach (CuisineType c in (CuisineType[]) Enum.GetValues(typeof(CuisineType)))
                                    {
                                        if (@c==@res.Cuisine)
                                        {
                                            <option value="@Convert.ToInt32(c)" selected>@c</option>
                                        }
                                        else
                                        {
                                            <option value="@Convert.ToInt32(c)">@c</option>
                                        }
                                        
                                    }
            </select>
          </div>
         
          <div class="form-group">
         <select asp-for="@res.CuisineDays"class="form-control">
                          @foreach (CuisineDays c in (CuisineDays[]) Enum.GetValues(typeof(CuisineDays)))
                                             {
                                                 if (@c==@res.CuisineDays)
                                                 {
                                                     <option value="@Convert.ToInt32(c)" selected>@c</option>
                                                 }
                                                 else
                                                 {
                                                     <option value="@Convert.ToInt32(c)">@c</option>
                                                 }
                                             }
                     </select>
          </div>

         <div class="form-group">
             <label asp-for="Phone">Phone:</label>
             <input type="text" asp-for="Phone" class="form-control" value="@res.Phone"/>
             <span asp-validation-for="Phone" class="text-danger"></span>
         </div>
         
         
         <div class="form-group">
             <label asp-for="Description">Description:</label>
             <input type="text" asp-for="Description" class="form-control" value="@res.Description"/>
             <span asp-validation-for="Description" class="text-danger"></span>
         </div>

         <div class="form-group">
                      <input class="btn btn-success" type="submit" value="Update">
                      <a class="btn btn-danger" asp-action="Index" asp-controller="Home">Cancel</a>
                  </div>
         
     </form>
 </div>
 </div>
 </body>
 </html>

Views/Home/Create.cshtml
@using OdeToFood.Models
@model OdeToFood.Models.Restaurant

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers 

@{
     Layout = "_Layout";
 }
 
 <!DOCTYPE html>
 
 <html lang="html">
 <head>
     <title>Create</title>
 </head>
 <body>
 <div class="row justify-content-center pt-3">
 <div class="col-lg-5">
     <h1>Create new Restaurant</h1>
     @*You should change this form and use razor tags*@

     <form asp-action="Create" asp-controller="Home" method="post">
         
         <div class="form-group">
             <label asp-for="Name">Name</label>
             <input type="text" asp-for="Name" class="form-control"/>
             <small aria-invalid="true"></small>
         </div>

         <div class="form-group">
             <label asp-for="Location">Location:</label>
             <input type="text" asp-for="Location" class="form-control"/>
             <small aria-invalid="true"></small>
         </div>
         
          <div class="form-group">
<select asp-for="@Model.Cuisine" asp-items="Html.GetEnumSelectList<CuisineType>()" class="form-control">
                <option>Select cuisine</option>
            </select>
          </div>
         
          <div class="form-group">
         <select asp-for="@Model.CuisineDays" asp-items="Html.GetEnumSelectList<CuisineDays>()" class="form-control">
                         <option>Select days</option>
                     </select>
          </div>

         <div class="form-group">
             <label asp-for="Phone">Phone:</label>
             <input type="text" asp-for="Phone" class="form-control"/>
             <span asp-validation-for="Phone" class="text-danger"></span>
         </div>
         
         <div class="form-group">
              <label asp-for="Description">Description:</label>
             <textarea asp-for="Description" cols="3" class="form-control"></textarea>
  <span asp-validation-for="Description" class="text-danger"></span>
         </div>
         
         
         <div class="form-group">
                      <input class="btn btn-success" type="submit" value="Save">
                      <input class="btn btn-danger" type="reset" value="Clear form">
                  </div>
         
     </form>
 </div>
 </div>
 </body>
 </html>

Views/Home/Details.cshtml
@model OdeToFood.Models.Restaurant
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers 
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title>Home</title>
</head>
<body>

<div class="row justify-content-center pt-5 pb-5">
    <div class="col-lg-5">
        <div class="card" style="width: 30rem;">
            <img class="card-img-top" src="https://pngimage.net/wp-content/uploads/2018/06/restaurants-logo-png-3.png" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@Model.Name</h5>
                <p class="card-text">@Model.Description</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>Cuisine:</b> @Model.Cuisine</li>
                <li class="list-group-item"><b>Location:</b> @Model.Location</li>
                <li class="list-group-item"><b>Phone:</b> @Model.Phone</li>
                <li class="list-group-item"><b>Working days:</b> @Model.CuisineDays</li>
        
            </ul>
            <div class="card-body">
                <a class="btn btn-info" asp-action="Update" asp-controller="About" asp-route-id="@Model.Id">Update</a>
                <button class="btn btn-danger ml-2 mr-2" data-toggle="modal" data-target="#exampleModal" >Delete</button>
                <a class="btn btn-success" asp-action="Index" asp-controller="Home">All restaurants</a>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete warning</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       Are you sure you need to delete this restaurant?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a class="btn btn-danger" asp-controller="About" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
      </div>
    </div>
  </div>
</div>


</body>
</html>

Views/Home/Index.cshtml
@model OdeToFood.ViewModels.HomeViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers 
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title>Home</title>
</head>
<body>
<div>
   
    <div>
        
        <div class="d-flex justify-content-between pt-5 pb-2">
            <h3>List of all restaurants</h3>
           
            <a class="btn btn-info" asp-action="Create" asp-controller="Home">New restaurant</a>
        
        </div>
        <table class="table table-striped">
            <thead class="thead-dark">
            <th>ID</th>
            <th>Name</th>
            <th>Location</th>
            <th colspan="3">Action</th>
            </thead>
            @* @foreach (var resto in Model) *@
            @foreach (var resto in Model.Restaurants)
            {
                <tr>
                    <td>@resto.Id.ToString()</td>
                    <td>@resto.Name</td>
                    <td>@resto.Location</td>
                    <td>@Html.ActionLink("Details", "Details", new {id = resto.Id})</td>

                </tr>
            }
        </table>

    </div>
</div>
</body>
</html>

Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers 

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">ODE TO FOOD</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" asp-action="Index" asp-controller="Home">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" asp-action="Help" asp-controller="About">Help</a>
    </div>
  </div>
</nav>

<div class="container">
@RenderBody()
</div>

</body>

 <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</html>